# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
#
name: Build Docker Image

on:
  push:
      tags:
      - 'v*' # 仅当推送的标签匹配 v* 模式时触发

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_SRC: registry.cn-hangzhou.aliyuncs.com/liaozhiming

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的 Git 历史记录，包括标签

      - name: Get project name
        id: get_project_name
        run: |
          repo_name=${GITHUB_REPOSITORY##*/}
          echo "repo_name=$repo_name" >> $GITHUB_ENV

      - name: Get latest tag and Remove 'v' prefix from tag
        id: get_latest_tag
        run: |
          # 获取最新的标签（假设标签都是按字母顺序排序的，并且最新的标签排在最前面）
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest tag: $latest_tag"
          # 去掉标签中的 "v" 前缀（如果存在）  
          latest_tag_without_v=$(echo "$latest_tag" | sed 's/^v//') 
          # 将处理后的标签设置为输出变量  
          echo "latest_tag_without_v=$latest_tag_without_v" >> $GITHUB_ENV

      - name: 构建Docker镜像
        run: |
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag ${{ env.IMAGE_SRC }}/${{ env.repo_name }}:${{ env.latest_tag_without_v }}
          # 给镜像打标签
          docker tar ${{ env.IMAGE_SRC }}/${{ env.repo_name }}:${{ env.latest_tag_without_v }} ${{ env.IMAGE_SRC }}/${{ env.repo_name }}:latest

      # Slim the Image
      - uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: ${{ env.IMAGE_SRC }}/${{ env.repo_name }}:latest
          tag: ${{ env.latest_tag_without_v }}_{{github.run_number}}_slim

      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker images
          # 推送镜像到镜像仓库
          docker image push ${{ env.IMAGE_SRC }}/${{ env.repo_name }} --all-tags

