# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
#
name: Build Docker Image

on:
  # 在针对 `main` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的 Git 历史记录，包括标签

      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/liaozhiming/nginx:temp
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/liaozhiming/nginx:temp

